@startwbs
* XX项目
** 需求阶段

*** 需求调研
*** 需求规格
*** 需求评审

** 设计阶段
*** 概要设计
*** 详细设计
*** 设计评审

** 开发阶段
*** 编码
*** 代码审查
*** 单元测试

** 测试阶段
*** 模块测试
*** 集成测试
*** 产品发布

** 维护阶段
*** 缺陷报告
*** 缺陷修复
*** 产品迭代
@endwbs