@startuml
title 交易系统生单时序图
autonumber
业务方 -> 商品服务: 获取商品
商品服务 -> 业务方: 商品列表
业务方 -> 售前服务: 优惠券计算
售前服务 -> 业务方: 优惠券列表
业务方 -> 订单服务: 创建订单
订单服务 -> 支付服务: 创建支付单
支付服务 -> 订单服务: 完全支付
订单服务 -> 发货服务: 创建发货单
发货服务 -> 业务方: 通知发货
业务方 -> 发货服务: 发货结果，变更发货单状态
发货服务 -> 订单服务: 变更订单发货状态，订单完结
订单服务 -> 支付服务: 订单完结
订单服务 -> 业务方: 订单完结
@enduml